# This workflow will generate html documentation from asciidoc and publish it to `gh-pages` branch
name: Deploy documentation
on:
  push:
    branches:
      - main

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch [main]
        uses: actions/checkout@v3
        with:
          ref: main
#      - name: Push [main] to [gh-pages]
#        shell: bash
#        run: git push origin main:gh-pages --force
#      - name: Checkout [gh-pages]
#        uses: actions/checkout@v3
#        with:
#          ref: gh-pages
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: 11
#          distribution: 'temurin'
      # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
      - name: Generate with asciidoctor image
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pdf_build: true
          # asciidoctor_params: --attribute=nofooter
          # adoc_file_ext: .ascii # default is .adoc
          source_dir: docs/ # default is .
          # slides_build: true
          # pre_build:
          # post_build:
#      - name: Generate docs with Maven
#        run: |
#          mvn org.asciidoctor:asciidoctor-maven-plugin:2.2.2:process-asciidoc \
#          -Dasciidoctor.sourceDirectory=./docs \
#          -Dasciidoctor.outputDirectory=. \
#          -Dasciidoctor.preserveDirectories=true \
#          -Dasciidoctor.sourceHighlighter=coderay \
#          -Dasciidoctor.backend=html5 \
#          -Dasciidoctor.requires=asciidoctor-diagram
      - name: Commit and push to [gh-pages]
        shell: bash
        run: |
          git config --global user.email "opensource@icellmobilsoft.hu"
          git config --global user.name "Github Action - Deploy documentation"
          git add .
          git commit -m "Add auto-generated documentation"
          git push origin gh-pages --force